In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot
df=pd.read_csv("abalone.csv")
df

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [2]:
pd.isnull(df).sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole weight      0
Shucked weight    0
Viscera weight    0
Shell weight      0
Rings             0
dtype: int64

In [3]:
#df.drop("Sex",axis='columns', inplace=True)

In [4]:
#import tensorflow as tf
x=df.iloc[:,1:-1]
y=df.iloc[:,-1]

#np.array(*your list*, dtype=np.float)
x,y=x,y.astype("float")
#x,y=tf.convert_to_tensor(x,y)
#n_features=x.shape[1]

In [5]:
x.shape[1]

7

In [10]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model=Sequential()
model.add(Dense(20,input_dim=7,activation="relu",kernel_initializer="he_normal"))
model.add(Dense(10,activation="relu",kernel_initializer="he_normal"))
model.add(Dense(1,activation='linear'))

model.compile(loss='mse',optimizer='adam')

model.fit(x_train,y_train,epochs=50,batch_size=32,verbose=2)

Epoch 1/50
105/105 - 1s - loss: 114.0251
Epoch 2/50
105/105 - 0s - loss: 71.6792
Epoch 3/50
105/105 - 0s - loss: 11.1544
Epoch 4/50
105/105 - 0s - loss: 7.3066
Epoch 5/50
105/105 - 0s - loss: 7.0697
Epoch 6/50
105/105 - 0s - loss: 6.8751
Epoch 7/50
105/105 - 0s - loss: 6.6911
Epoch 8/50
105/105 - 0s - loss: 6.5643
Epoch 9/50
105/105 - 0s - loss: 6.4527
Epoch 10/50
105/105 - 0s - loss: 6.3717
Epoch 11/50
105/105 - 0s - loss: 6.2874
Epoch 12/50
105/105 - 0s - loss: 6.2197
Epoch 13/50
105/105 - 0s - loss: 6.1501
Epoch 14/50
105/105 - 0s - loss: 6.0885
Epoch 15/50
105/105 - 0s - loss: 5.9751
Epoch 16/50
105/105 - 0s - loss: 5.8469
Epoch 17/50
105/105 - 0s - loss: 5.7559
Epoch 18/50
105/105 - 0s - loss: 5.6458
Epoch 19/50
105/105 - 0s - loss: 5.5727
Epoch 20/50
105/105 - 0s - loss: 5.4826
Epoch 21/50
105/105 - 0s - loss: 5.4161
Epoch 22/50
105/105 - 0s - loss: 5.3593
Epoch 23/50
105/105 - 0s - loss: 5.2804
Epoch 24/50
105/105 - 0s - loss: 5.2496
Epoch 25/50
105/105 - 0s - loss: 5.2095
Epoch 26/50
105/105 - 0s - loss: 5.1596
Epoch 27/50
105/105 - 0s - loss: 5.0980
Epoch 28/50
105/105 - 0s - loss: 5.0709
Epoch 29/50
105/105 - 0s - loss: 5.0203
Epoch 30/50
105/105 - 0s - loss: 5.0199
Epoch 31/50
105/105 - 0s - loss: 5.0112
Epoch 32/50
105/105 - 0s - loss: 4.9931
Epoch 33/50
105/105 - 0s - loss: 4.9364
Epoch 34/50
105/105 - 0s - loss: 4.9025
Epoch 35/50
105/105 - 0s - loss: 4.9076
Epoch 36/50
105/105 - 0s - loss: 4.8794
Epoch 37/50
105/105 - 0s - loss: 4.8525
Epoch 38/50
105/105 - 0s - loss: 4.8599
Epoch 39/50
105/105 - 0s - loss: 4.8301
Epoch 40/50
105/105 - 0s - loss: 4.8422
Epoch 41/50
105/105 - 0s - loss: 4.8326
Epoch 42/50
105/105 - 0s - loss: 4.8157
Epoch 43/50
105/105 - 0s - loss: 4.8003
Epoch 44/50
105/105 - 0s - loss: 4.7795
Epoch 45/50
105/105 - 0s - loss: 4.7645
Epoch 46/50
105/105 - 0s - loss: 4.7528
Epoch 47/50
105/105 - 0s - loss: 4.7571
Epoch 48/50
105/105 - 0s - loss: 4.7394
Epoch 49/50
105/105 - 0s - loss: 4.7663
Epoch 50/50
105/105 - 0s - loss: 4.7337

In [11]:
predict=model.predict(x_test)
error1=mean_squared_error(y_test,predict)
error2=mean_absolute_error(y_test,predict)
print('MSE=%3f'%error1)
print('MAE=%3f'%error2)

MSE=4.649892
MAE=1.560874